### PR TITLE
Replace environ_overrides

### PR DESCRIPTION
**Pull request by Satoshi-Sh**
## Updates
- Tried the middleware approach suggested by Robbe [here](url) . This is not working as expected. My implementation might be wrong.
- As mentioned  [here](https://github.com/apache/airflow/pull/36052#:~:text=connexion%27s%20test_client().-,I%20didn%27t%20find%20any%20equivalent%20in%20Connexion%20and%20Starlette%20docs.%20%40RobbeSneyders%20could%20you%20help%20us%20with%20that%3F,-AttributeError%3A%20%27Response%27%20object) by Maks, I cannot find any information about environ_overrides in starlette or connexion. I happened to find environ_overrides in [werkzeug doc](https://werkzeug.palletsprojects.com/en/2.3.x/test/#:~:text=environ_overrides%20(t.Mapping%5Bstr%2C%20t.Any%5D%20%7C%20None)%20%E2%80%93%20an%20optional%20dict%20of%20environment%20overrides.). It might have something to do with the test_client stopping taking environ_overrides argument?

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by Satoshi-Sh** [comment]
## What I found so far 

I still cannot find a way to replace environ_overrides. 

The main problem is that I cannot make http requests as a "user" or "test_no_permissions" after removing the envrion_overrides argument from the `self.client.get()`.  I tried the middleware approach suggested by Robbe. It doesn't work as expected. 
`remote_user_api_auth_backend.py`
 ```def requires_authentication(function: T):
    """Decorator for functions that require authentication"""

    @wraps(function)
    def decorated(*args, **kwargs):
        user_id = request.remote_user
        if not user_id:
            log.debug("Missing REMOTE_USER.")
            return Response("Forbidden", 403)

        log.debug("Looking for user: %s", user_id)

        user = _lookup_user(user_id)
        if not user:
            return Response("Forbidden", 403)

        log.debug("Found user: %s", user)

        login_user(user, remember=False)
        return function(*args, **kwargs)

    return cast(T, decorated)
```
After setting up the middleware, I changed `user_id = request.remote_user` like request.scope.remote_user but I get the request doesn't have a scope attribute.

**Comment by Satoshi-Sh** [comment]
## Approach without using the Middleware

I moved the {"REMOTE_USER":"test"} to headers and change `user_id = request.headers.get("REMOTE-USER")` from `user_id=request.remote_user` in the  remote_user_api_auth_backend.py

This approach works fine on the main branch, but I get the error `request doesn't have data attribute` on this connexion v3 branch, so I needed to request.text.  

I'm not sure if this approach is proper to simulate the tests.

**Comment by potiuk** [comment]
> I'm not sure if this approach is proper to simulate the tests.

Looks definitely good to me :)

**Comment by Satoshi-Sh** [comment]
Thanks for checking it, Jarek. I will start rewriting tests tomorrow.

**Comment by Satoshi-Sh** [comment]
## Updates
- Mainly replaced environ_overides errors and made some easy fixes to let it pass the tests.  
- Some files have issues other than environ_overrides. We need to investigate the errors.

**Pull request merged**
